version: '3'

services:
  db:
    container_name: "golangtest_db"
    image: "postgres:16.2-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=golangtest_username
      - POSTGRES_PASSWORD=golangtest_password
      - POSTGRES_DB=golangtest_db
    volumes:
      - golangtest_db_data:/var/lib/postgresql/data

volumes:
  golangtest_db_data: {}
